# Usa una imagen base de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia todos los archivos necesarios al contenedor
# COPY shell_logger.py  .
# COPY model.py .
COPY . .

# Instala las dependencias necesarias
RUN pip install peewee

RUN apt-get update && apt-get install -y bash

# Comando para ejecutar ambos scripts
ENTRYPOINT ["python", "shell_logger.py"]